owner: LittleLink-Custom
repo: uptime
user-agent: LLC_uptime

sites:
  - name: Website
    url: https://littlelink-custom.com
    assignees:
     - JulianPrieber
  - name: Demo
    url: https://demo.littlelink-custom.com
    icon:
    assignees:
     - JulianPrieber
  - name: LLC Update Server
    url: https://update.littlelink-custom.com
    icon:
    assignees:
     - JulianPrieber
  - name: LLC Version Server
    url: https://version.littlelink-custom.com
    icon:
  - name: LLC Event Server
    url: https://event.littlelink-custom.com
    icon:
  - name: LLC Beta Server
    url: https://beta.littlelink-custom.com
    icon:
    assignees:
     - JulianPrieber
  - name: llc.bio
    url: https://llc.bio
    icon:
  - name: LLC Test Server
    url: $TEST_SERVER
    icon:

status-website:
  cname: uptime.littlelink-custom.com
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/LittleLink-Custom/branding/main/logo/svg/logo.svg
  name: LLC Uptime
  faviconSvg: https://raw.githubusercontent.com/LittleLink-Custom/branding/main/logo/svg/logo.svg
  favicon: https://raw.githubusercontent.com/LittleLink-Custom/branding/main/logo/png/logo_lowres.png
  scripts:
    - src:
      async: true
  introTitle: "LLC Uptime"
  introMessage: Check if any part of LittleLink-Custom is down
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://littlelink-custom.com
  theme: night
  # themeUrl: https://littlelink-custom.github.io/uptime/llc.css
