# Change these first
owner: LittleLink-Custom # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
user-agent: LLC_uptime

sites:
  - name: Website
    url: https://littlelink-custom.com
    assignees:
     - JulianPrieber
  - name: Demo
    url: https://demo.littlelink-custom.com
    icon:
    assignees:
     - JulianPrieber
  - name: LLC Update Server
    url: https://update.littlelink-custom.com
    icon:
    assignees:
     - JulianPrieber
  - name: LLC Version Server
    url: https://version.littlelink-custom.com
    icon:
  - name: LLC Event Server
    url: https://event.littlelink-custom.com
    icon:
  - name: LLC Beta Server
    url: https://beta.littlelink-custom.com
    icon:
    assignees:
     - JulianPrieber
  - name: llc.bio
    url: https://llc.bio
    icon:
    assignees:
     - JulianPrieber

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime.littlelink-custom.com
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LLC Uptime
  introTitle: "LLC Uptime"
  introMessage: Check if any part of LittleLink-Custom is down
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://littlelink-custom.com
  theme: night
  # themeUrl: https://littlelink-custom.github.io/uptime/llc.css
  scripts:
    - src:
      async: true
  faviconSvg:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
